### ISSUE TITLE
HU-002 - TA - 001 Hacer formulario para el registro de una venta

### ISSUE THREAD

**Issue by abrilonia** [abrilonia/Mesa-Lista-App#4]
- Debe llevar la **fecha**, que los **productos** se desplieguen de una **lista**, el **precio**, **cantidad**, **subtotal** y **total final**, así como el **método de pago** de una lista también.

- Colores: negro, blanco, azul intenso pero solo para detalles pequeños, la idea es que sea muy genérico para venderlo y usarlo en varios tipos de negocios.
-
- Si es posible en los botones usar imágenes referente a la acción que hace el botón o lo que se refiere esa casilla por ejemplo, el tipo de pago poner un billete, pero íconos pequeños.

**Comment by LucasA75** [comment]
Voy a hacer esto , no hiciste el Proyects ?

**Comment by abrilonia** [comment]
Ya te agregué como colaborador aquí.

**Comment by LucasA75** [comment]
Pregunta: Quieres que lo haga funcional ???
